RAW_HEADER_ORDER = [9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 10]
FORMATTED_HEADERS = [
    'Id',
    'Status',
    'First Name',
    'Last Name',
    'Primary Phone',
    'Email',
    'Profile',
    'Password Last Changed',
    'Created',
    'Activated',
    'Last Updated',
    'Link',
    'Last Login',
    'Credentials',
    'Status Changed'
]
OKTA_IMPORT_FIELDS = [
    'login',
    'firstName',
    'lastName',
    'middleName',
    'honorificPrefix',
    'honorificSuffix',
    'email',
    'title',
    'displayName',
    'nickName',
    'profileUrl',
    'secondEmail',
    'mobilePhone',
    'primaryPhone',
    'streetAddress',
    'city',
    'state',
    'zipCode',
    'countryCode',
    'postalAddress',
    'preferredLanguage',
    'locale',
    'timezone',
    'userType',
    'employeeNumber',
    'costCenter',
    'organization',
    'division',
    'department',
    'managerId',
    'manager',
    'role',
    'company',
    'streetAddress2',
    'country',
    'passwordHash',
    'ppids',
    'gid',
    'salutation'
]
